# kubectl apply -f k8s.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: vaxxlink
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: vaxxlink-ingress
  namespace: vaxxlink
spec:
  rules:
  - host: api.vaxx.link
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaxxlink
            port:
              number: 80
  tls:
  - hosts:
    - api.vaxx.link
    secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: vaxxlink
  name: vaxxlink
spec:
  selector:
    app: vaxxlink
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaxxlink
  namespace: vaxxlink
  labels:
    app: vaxxlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaxxlink
  template:
    metadata:
      labels:
        app: vaxxlink
    spec:
      securityContext:
        fsGroup: 2000
      volumes:
      - name: vaxxdb
        persistentVolumeClaim:
          claimName: vaxxlink-db-managed-disk
      containers:
      - name: shlapi
        image: ghcr.io/jmandel/vaxxlink:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: PUBLIC_URL
          value: "https://api.vaxx.link"
        volumeMounts:
        - mountPath: "/app/db"
          name: vaxxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaxxlink-db-managed-disk
  namespace: vaxxlink
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
apiVersion: v1
