name: Deploy Server to k8s
on:
  workflow_dispatch:
  push:
    branches:
    - main
#    paths:
#    - 'server/**'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    environment: k8deploy
    runs-on: ubuntu-latest
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and rollout to CI
      working-directory: ./server
      run: |
        docker build . \
          -t ghcr.io/jmandel/vaxxlink:$GITHUB_SHA \
          -t ghcr.io/jmandel/vaxxlink:latest
        docker push ghcr.io/jmandel/vaxxlink
        # kubectl -n vaxxlink rollout restart deployment/vaxxlink
